version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_survey
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    build: .
    container_name: go_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: users_survey
      DB_PORT: 5432
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "sleep 5 && go run main.go"

volumes:
  pgdata:
