// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type User struct {
	ID       int32
	Name     string
	Age      int32
	Gender   string
	Email    string
	Password []byte
}

type UserGeneration struct {
	ID         int32
	UserID     int32
	Generation string
	Grade      string
}
